"""Export modules for various bitmap font formats."""

from typing import List
from pathlib import Path
from .rasterizer import GlyphBitmap


class ExporterError(Exception):
    """Exception raised for export errors."""
    pass


class BaseExporter:
    """Base class for font exporters."""

    def __init__(self, font_name: str = "CustomFont"):
        """Initialize the exporter.

        Args:
            font_name: Name to use in exported files
        """
        self.font_name = self._sanitize_name(font_name)

    @staticmethod
    def _sanitize_name(name: str) -> str:
        """Sanitize font name for use in code.

        Args:
            name: Original font name

        Returns:
            Sanitized name safe for use in code
        """
        # Replace spaces and special chars with underscores
        sanitized = ''.join(c if c.isalnum() else '_' for c in name)
        # Remove leading digits
        if sanitized and sanitized[0].isdigit():
            sanitized = 'Font_' + sanitized
        return sanitized or 'CustomFont'

    def export(self, glyphs: List[GlyphBitmap], output_path: str) -> None:
        """Export glyphs to file.

        Args:
            glyphs: List of rasterized glyphs
            output_path: Path to output file

        Raises:
            ExporterError: If export fails
        """
        raise NotImplementedError("Subclasses must implement export()")


class CHeaderExporter(BaseExporter):
    """Exports font data as C header file (Adafruit GFX compatible)."""

    def export(self, glyphs: List[GlyphBitmap], output_path: str) -> None:
        """Export glyphs to C header file.

        Format is compatible with Adafruit GFX library.

        Args:
            glyphs: List of rasterized glyphs
            output_path: Path to output .h file
        """
        if not glyphs:
            raise ExporterError("No glyphs to export")

        lines = []
        lines.append(f"// Font: {self.font_name}")
        lines.append(f"// Generated by Minifont")
        lines.append(f"// Characters: {len(glyphs)}")
        lines.append("")
        lines.append("#ifndef _" + self.font_name.upper() + "_H_")
        lines.append("#define _" + self.font_name.upper() + "_H_")
        lines.append("")
        lines.append("#include <stdint.h>")
        lines.append("")

        # Export bitmap data
        lines.append(f"const uint8_t {self.font_name}Bitmaps[] PROGMEM = {{")

        bitmap_offset = 0
        offsets = []

        for glyph in glyphs:
            if glyph.width == 0 or glyph.height == 0:
                offsets.append(bitmap_offset)
                continue

            comment = f"  // '{glyph.char}' (U+{glyph.char_code:04X})"
            lines.append(comment)

            # Convert bitmap to hex bytes
            hex_bytes = ', '.join(f"0x{b:02X}" for b in glyph.bitmap)
            lines.append(f"  {hex_bytes},")

            offsets.append(bitmap_offset)
            bitmap_offset += len(glyph.bitmap)

        lines.append("};")
        lines.append("")

        # Export glyph metadata
        lines.append(f"const struct {{")
        lines.append(f"  uint16_t bitmapOffset;  // Pointer into {self.font_name}Bitmaps")
        lines.append(f"  uint8_t width;          // Bitmap width in pixels")
        lines.append(f"  uint8_t height;         // Bitmap height in pixels")
        lines.append(f"  uint8_t xAdvance;       // Distance to advance cursor (x axis)")
        lines.append(f"  int8_t xOffset;         // X offset of glyph in bitmap")
        lines.append(f"  int8_t yOffset;         // Y offset of glyph in bitmap")
        lines.append(f"}} {self.font_name}Glyphs[] PROGMEM = {{")

        for i, glyph in enumerate(glyphs):
            lines.append(
                f"  {{ {offsets[i]}, {glyph.width}, {glyph.height}, "
                f"{glyph.advance_x}, {glyph.offset_x}, {glyph.offset_y} }}, "
                f"// '{glyph.char}' (U+{glyph.char_code:04X})"
            )

        lines.append("};")
        lines.append("")

        # Export character mapping
        first_char = min(g.char_code for g in glyphs)
        last_char = max(g.char_code for g in glyphs)

        lines.append(f"const struct {{")
        lines.append(f"  uint16_t first;   // First character code")
        lines.append(f"  uint16_t last;    // Last character code")
        lines.append(f"}} {self.font_name}Range PROGMEM = {{")
        lines.append(f"  {first_char}, {last_char}")
        lines.append("};")
        lines.append("")

        lines.append("#endif // _" + self.font_name.upper() + "_H_")

        # Write to file
        try:
            Path(output_path).write_text('\n'.join(lines))
        except Exception as e:
            raise ExporterError(f"Failed to write C header: {e}")


class XBMExporter(BaseExporter):
    """Exports font data as XBM format (U8g2 compatible)."""

    def export(self, glyphs: List[GlyphBitmap], output_path: str) -> None:
        """Export glyphs to XBM file.

        Args:
            glyphs: List of rasterized glyphs
            output_path: Path to output .xbm file
        """
        if not glyphs:
            raise ExporterError("No glyphs to export")

        # Calculate total bitmap dimensions
        total_width = sum(g.width for g in glyphs)
        max_height = max((g.height for g in glyphs), default=0)

        lines = []
        lines.append(f"// Font: {self.font_name}")
        lines.append(f"// Characters: {len(glyphs)}")
        lines.append(f"#define {self.font_name}_width {total_width}")
        lines.append(f"#define {self.font_name}_height {max_height}")
        lines.append(f"static unsigned char {self.font_name}_bits[] = {{")

        # Export all bitmaps
        all_bytes = []
        for glyph in glyphs:
            all_bytes.extend(glyph.bitmap)

        # Format as XBM hex data
        for i in range(0, len(all_bytes), 12):
            chunk = all_bytes[i:i+12]
            hex_str = ', '.join(f"0x{b:02X}" for b in chunk)
            lines.append(f"  {hex_str},")

        lines.append("};")

        # Write to file
        try:
            Path(output_path).write_text('\n'.join(lines))
        except Exception as e:
            raise ExporterError(f"Failed to write XBM file: {e}")


class BDFExporter(BaseExporter):
    """Exports font data as BDF (Bitmap Distribution Format)."""

    def __init__(self, font_name: str = "CustomFont", font_size: int = 16):
        """Initialize BDF exporter.

        Args:
            font_name: Name to use in exported file
            font_size: Font size in pixels
        """
        super().__init__(font_name)
        self.font_size = font_size

    def export(self, glyphs: List[GlyphBitmap], output_path: str) -> None:
        """Export glyphs to BDF file.

        Args:
            glyphs: List of rasterized glyphs
            output_path: Path to output .bdf file
        """
        if not glyphs:
            raise ExporterError("No glyphs to export")

        lines = []

        # BDF header
        lines.append("STARTFONT 2.1")
        lines.append(f"FONT {self.font_name}")
        lines.append(f"SIZE {self.font_size} 75 75")
        lines.append("FONTBOUNDINGBOX 16 16 0 0")
        lines.append("STARTPROPERTIES 2")
        lines.append(f"FONT_ASCENT {self.font_size}")
        lines.append("FONT_DESCENT 0")
        lines.append("ENDPROPERTIES")
        lines.append(f"CHARS {len(glyphs)}")

        # Export each glyph
        for glyph in glyphs:
            lines.append("STARTCHAR " + (glyph.char if 32 <= glyph.char_code <= 126 else f"U+{glyph.char_code:04X}"))
            lines.append(f"ENCODING {glyph.char_code}")
            lines.append(f"SWIDTH {glyph.advance_x * 1000 // self.font_size} 0")
            lines.append(f"DWIDTH {glyph.advance_x} 0")
            lines.append(f"BBX {glyph.width} {glyph.height} {glyph.offset_x} {glyph.offset_y}")
            lines.append("BITMAP")

            # Convert bitmap to hex strings
            if glyph.width == 0 or glyph.height == 0:
                lines.append("00")
            else:
                # Use pitch from glyph for correct row alignment
                bytes_per_row = (glyph.width + 7) // 8
                for row in range(glyph.height):
                    # Use pitch to calculate row offset, but only export bytes_per_row bytes
                    row_offset = row * glyph.pitch
                    row_bytes = glyph.bitmap[row_offset:row_offset + bytes_per_row]
                    hex_str = ''.join(f"{b:02X}" for b in row_bytes)
                    lines.append(hex_str or "00")

            lines.append("ENDCHAR")

        lines.append("ENDFONT")

        # Write to file
        try:
            Path(output_path).write_text('\n'.join(lines))
        except Exception as e:
            raise ExporterError(f"Failed to write BDF file: {e}")


class PythonExporter(BaseExporter):
    """Exports font data as Python byte arrays (MicroPython compatible)."""

    def export(self, glyphs: List[GlyphBitmap], output_path: str) -> None:
        """Export glyphs to Python file.

        Args:
            glyphs: List of rasterized glyphs
            output_path: Path to output .py file
        """
        if not glyphs:
            raise ExporterError("No glyphs to export")

        lines = []
        lines.append(f"# Font: {self.font_name}")
        lines.append(f"# Generated by Minifont")
        lines.append(f"# Characters: {len(glyphs)}")
        lines.append("")

        # Export bitmap data
        lines.append(f"{self.font_name}_bitmaps = bytes([")

        for glyph in glyphs:
            if glyph.width == 0 or glyph.height == 0:
                continue

            comment = f"    # '{glyph.char}' (U+{glyph.char_code:04X})"
            lines.append(comment)

            hex_bytes = ', '.join(f"0x{b:02X}" for b in glyph.bitmap)
            lines.append(f"    {hex_bytes},")

        lines.append("])")
        lines.append("")

        # Export glyph metadata
        lines.append(f"{self.font_name}_glyphs = [")

        for glyph in glyphs:
            lines.append(
                f"    ({glyph.char_code}, {glyph.width}, {glyph.height}, "
                f"{glyph.advance_x}, {glyph.offset_x}, {glyph.offset_y}),  "
                f"# '{glyph.char}'"
            )

        lines.append("]")

        # Write to file
        try:
            Path(output_path).write_text('\n'.join(lines))
        except Exception as e:
            raise ExporterError(f"Failed to write Python file: {e}")
