/**
 * Arduino Example: Using Minifont-generated font data
 *
 * This example shows how to use a C header file generated by Minifont
 * with Adafruit GFX library on Arduino.
 *
 * Hardware: Arduino with display (e.g., SSD1306 OLED)
 * Libraries: Adafruit_GFX, Adafruit_SSD1306 (or compatible)
 */

#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>

// Include the generated font header
// (Generate this using: minifont --font myfont.ttf --size 16 --charset ascii --format c-header --output myfont16.h)
#include "myfont16.h"

#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64
#define OLED_RESET -1

Adafruit_SSD1306 display(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, OLED_RESET);

void setup() {
  Serial.begin(9600);

  // Initialize display
  if(!display.begin(SSD1306_SWITCHCAPVCC, 0x3C)) {
    Serial.println(F("SSD1306 allocation failed"));
    for(;;);
  }

  display.clearDisplay();
  display.setTextColor(SSD1306_WHITE);

  // Note: Custom font implementation would go here
  // The generated header provides bitmap data that needs to be
  // rendered manually or integrated with a custom GFX font structure

  display.setCursor(0, 0);
  display.println(F("Minifont Demo"));
  display.println(F("Custom Font"));

  display.display();
}

void loop() {
  // Your code here
  delay(1000);
}

/**
 * Custom font rendering function (example)
 *
 * To use the generated font data, you would typically:
 * 1. Read character code from your string
 * 2. Look up glyph data in MyFontGlyphs array
 * 3. Get bitmap data from MyFontBitmaps using bitmapOffset
 * 4. Draw the bitmap at current cursor position
 * 5. Advance cursor by xAdvance
 */
void drawCustomChar(char c, int x, int y) {
  // Example pseudocode:
  // uint16_t charCode = (uint16_t)c;
  // if (charCode >= MyFontRange.first && charCode <= MyFontRange.last) {
  //   uint16_t index = charCode - MyFontRange.first;
  //   uint16_t offset = pgm_read_word(&MyFontGlyphs[index].bitmapOffset);
  //   uint8_t w = pgm_read_byte(&MyFontGlyphs[index].width);
  //   uint8_t h = pgm_read_byte(&MyFontGlyphs[index].height);
  //   // Draw bitmap from MyFontBitmaps[offset] at position (x, y)
  // }
}

/**
 * Using Minifont with U8g2 library:
 *
 * If you prefer U8g2 library, generate XBM format instead:
 * minifont --font myfont.ttf --size 16 --charset ascii --format xbm --output myfont16.xbm
 *
 * Then use u8g2.drawXBM() to display the font bitmaps.
 */
